<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInite8b18cf875fbd418ee3f4ca3e029a1d1
{
    public static $prefixLengthsPsr4 = array (
        'N' => 
        array (
            'Nrwtaylor\\StackAgentThing\\' => 26,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Nrwtaylor\\StackAgentThing\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
            1 => __DIR__ . '/../..' . '/agents',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInite8b18cf875fbd418ee3f4ca3e029a1d1::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInite8b18cf875fbd418ee3f4ca3e029a1d1::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
