
<meta name="viewport" content="width=device-width" />
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Stackr</title>
        <link rel="stylesheet" href="/style.css?70" type='text/css'>
    </head>
    <body>


<header>
<h1 class="front">Stackr</h1>

        <div class="card why">technology to get things done</div>

<div class="card how">
        <?php if (isset($messages)) : ?>
            <h2></h2>
        <?php else: ?>

        <?php endif; ?>
</div>

<div class="card response">
        <?php if (isset($name)) : ?>
        <h2><?= htmlspecialchars($name); ?>!</h2>  
       <!--     <h2>Hello.</h2> -->

        <?php else: ?>
</div>
</header>
<main class="grid">
<article>
<div class="card smsmessage">
<br>
<br>

            <!--<p><a href="mailto:just_send_this_email_to@stackr.ca">just_send_this_email_to@stackr.ca</a>-->
        <?php endif; ?>

<?php
//           $messages[0] = "Down for maintenance.";
//            $messages[0] = "Service announcement. US and Canada SMS is delayed. Reported at 13 March 2018 12:54.";
//            $messages[0] = "Service announcement. Translink realtime information is currently not available. Reported at 2 May 2019 16:53. All other services operating normally.";
//            $messages[0] = "Service announcement. SMS responder service is currently not available. Reported at 11 December 2019 22:41. All other services operating normally.";
//            $messages[0] = "Service announcement. SMS responder service is currently not available. Reported at 14 December 2019 22:44. All other services operating normally.";
//            $messages[0] = "Service announcement. SMS responder service is currently not available. Reported at 16 December 2019 13:54. All other services operating normally.";

            $messages[0] = "Text START to Vancouver, BC SMS Portal <br>at (778) 401-2132";

//            $messages[1] = "Use Stackr by email.  Request access to limitedbeta@stackr.ca.";


//            $messages[2] = "Hello.";


            $message = $messages[rand(0,count($messages) - 1)];

            $bubble = '<div class="triangle-border">' .$message . '</div>';
            echo quoted_printable_decode($bubble);
?>

</div>

<div class="card-buttons">
<?php
        // Display default button here

        $head= '
        <table class="makeweb">
        <tr>
        <td class="makeweb">
        <div class="buttonset">';

        $word = "Privacy";
        $url_link = "https://stackr.ca/privacy";

        $privacy_button = '<span class="button">
            <a style="text-decoration: none; color: white;" href="'.
                $url_link . '"> '.  ''. $word . ''.' </a></span>
            ';

//        $privacy_button = "";

        $word = "Terms of Use";
        $url_link = "https://stackr.ca/terms-of-use";

        $termsofuse_button = '<span class="button">
            <a style="text-decoration: none; color: white;" href="'.
                $url_link . '"> '.  ''. $word . ''.' </a></span>
            ';

        $foot = "
        </div>
        </td>
        </tr>
        </tbody>
        </table>";

$content =  '<table border="0" cellpadding="0" cellspacing="0" width="100%">
    <tbody>
        <tr>
            <td colspan="3" valign="top" width="15" height="10">
            </td>
        </tr>
        <tr style="line-height: 0">
            <td>
                <table style="border-spacing: 14px 0px">
                    <tr>
<td class="button">
            <a class="button" style="text-decoration: none; color: white;" href="https://stackr.ca/privacy"> Privacy </a>
</td>
</tr>
                </table>
            </td>
        </tr>

        <tr>
            <td colspan="3" valign="top" width="15" height="10">
            </td>
        </tr>
    </tbody>
</table>';


//$content =  '
//            <a style="text-decoration: none; color: white;" href="https://stackr.ca/privacy"><span class="button"> Privacy </span></a>
//';
$content = $privacy_button . $termsofuse_button;


//$content = "meep";

$head = '        <div>
        <table border="0" cellpadding="0" cellspacing="0" width="100%">
        <tbody>
        <tr>
        <td colspan="3" valign="top" width="15" height="10">
        </td>
        </tr>
        <tr class="buttonset">
        <td>
        <table class="buttonset">
        <tr>';

$foot = '       </tr>
        </table>
        </td>
        </tr>
        <tr>
        <td colspan="3" valign="top" width="15" height="10">
        </td>
        </tr>
        </tbody>
        </table>
        </div>';

        echo quoted_printable_decode($head);
        //echo '<div>';
        echo quoted_printable_decode($content);


        //echo "</div>";
        echo quoted_printable_decode($foot);



?>
</div>
</div>
</article>
<div class="card whatis">

A short message responder.

<br>短信机

<footer>


<br>
<br>
Unsubscribe: <a href="mailto:unsubscribe@stackr.ca">unsubscribe@stackr.ca</a>
<br>
Text STOP
<br>
<br>
</div>
<div class="card host">
Hosted in Canada
<br>
Stackr Interactive Ltd
<br>201-3701 Hastings Street, Burnaby, BC V5C 2H6
<br>
<br>
<div class="logo">
<center>
<img src="https://stackr.ca/pixel_sml.png">
</center>
</div>


<div class="card devstack">
<?php
    echo "#devstack";
    // Show the elapsed time
    if (isset($thing_report['start_time'])) {
        echo " ";
        $run_time = microtime(true) - $thing_report['start_time'];

        //microtime(true) returns time in seconds accurate to milliseconds

        $t = round($run_time * 1000000);

        if ($t > 999) {
            echo number_format(round($t/1000)). "ms";
        } else {
            echo number_format($t). "µs";
        }
    } 
    
?>
</div>

</footer>
</main>
    </body>
</html>
